- name: Configure keepalived on Docker Swarm nodes
  hosts: myhosts
  become: yes

  tasks:
    - name: Add ip_vs to /etc/modules
      lineinfile:
        path: /etc/modules
        line: 'ip_vs'
      notify: Load ip_vs module

    - name: Install python-docker package
      apt:
        name: python3-docker
        state: present

    - name: Start Docker container
      command: docker run -d --name keepalived --restart=always --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host -e KEEPALIVED_UNICAST_PEERS="{{ groups['myhosts'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list | to_json }}" -e KEEPALIVED_VIRTUAL_IPS=192.168.40.199 -e KEEPALIVED_PRIORITY="{{ 200 - (10 * ansible_play_hosts.index(inventory_hostname)) }}" -e KEEPALIVED_INTERFACE=ens18  osixia/keepalived:2.0.20
      loop_control:
        index_var: loop.index0

  handlers:
    - name: Load ip_vs module
      shell: modprobe ip_vs
